// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	[DataContract]
	public partial class ChatMessage : SpacetimeDB.DatabaseTableWithPrimaryKey<ChatMessage, SpacetimeDB.Types.ReducerEvent>
	{
		[DataMember(Name = "SenderId")]
		public ulong SenderId;
		[DataMember(Name = "Text")]
		public string? Text;

		private static Dictionary<ulong, ChatMessage> SenderId_Index = new(16);

		public override void InternalOnValueInserted()
		{
			SenderId_Index[SenderId] = this;
		}

		public override void InternalOnValueDeleted()
		{
			SenderId_Index.Remove(SenderId);
		}

		public static ChatMessage? FindBySenderId(ulong value)
		{
			SenderId_Index.TryGetValue(value, out var r);
			return r;
		}

		public static IEnumerable<ChatMessage> FilterBySenderId(ulong value)
		{
			if (FindBySenderId(value) is {} found)
			{
				yield return found;
			}
		}

		public override object GetPrimaryKeyValue() => SenderId;

	}
}
