// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	[DataContract]
	public partial class Config : SpacetimeDB.DatabaseTableWithPrimaryKey<Config, SpacetimeDB.Types.ReducerEvent>
	{
		[DataMember(Name = "Version")]
		public uint Version;
		[DataMember(Name = "MessageOfTheDay")]
		public string? MessageOfTheDay;

		private static Dictionary<uint, Config> Version_Index = new(16);

		public override void InternalOnValueInserted()
		{
			Version_Index[Version] = this;
		}

		public override void InternalOnValueDeleted()
		{
			Version_Index.Remove(Version);
		}

		public static Config? FindByVersion(uint value)
		{
			Version_Index.TryGetValue(value, out var r);
			return r;
		}

		public static IEnumerable<Config> FilterByVersion(uint value)
		{
			if (FindByVersion(value) is {} found)
			{
				yield return found;
			}
		}

		public override object GetPrimaryKeyValue() => Version;

	}
}
