// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	[DataContract]
	public partial class EntityComponent : SpacetimeDB.DatabaseTableWithPrimaryKey<EntityComponent, SpacetimeDB.Types.ReducerEvent>
	{
		[DataMember(Name = "EntityId")]
		public ulong EntityId;
		[DataMember(Name = "Position")]
		public SpacetimeDB.Types.StdbVector3 Position = new();
		[DataMember(Name = "Direction")]
		public float Direction;
		[DataMember(Name = "Moving")]
		public bool Moving;

		private static Dictionary<ulong, EntityComponent> EntityId_Index = new(16);

		public override void InternalOnValueInserted()
		{
			EntityId_Index[EntityId] = this;
		}

		public override void InternalOnValueDeleted()
		{
			EntityId_Index.Remove(EntityId);
		}

		public static EntityComponent? FindByEntityId(ulong value)
		{
			EntityId_Index.TryGetValue(value, out var r);
			return r;
		}

		public static IEnumerable<EntityComponent> FilterByEntityId(ulong value)
		{
			if (FindByEntityId(value) is {} found)
			{
				yield return found;
			}
		}

		public static IEnumerable<EntityComponent> FilterByDirection(float value)
		{
			return Query(x => x.Direction == value);
		}

		public static IEnumerable<EntityComponent> FilterByMoving(bool value)
		{
			return Query(x => x.Moving == value);
		}

		public override object GetPrimaryKeyValue() => EntityId;

	}
}
