// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	[DataContract]
	public partial class PlayerComponent : SpacetimeDB.DatabaseTableWithPrimaryKey<PlayerComponent, SpacetimeDB.Types.ReducerEvent>
	{
		[DataMember(Name = "EntityId")]
		public ulong EntityId;
		[DataMember(Name = "Identity")]
		public SpacetimeDB.Identity Identity = new();
		[DataMember(Name = "Username")]
		public string? Username;
		[DataMember(Name = "LoggedIn")]
		public bool LoggedIn;

		private static Dictionary<ulong, PlayerComponent> EntityId_Index = new(16);
		private static Dictionary<SpacetimeDB.Identity, PlayerComponent> Identity_Index = new(16);

		public override void InternalOnValueInserted()
		{
			EntityId_Index[EntityId] = this;
			Identity_Index[Identity] = this;
		}

		public override void InternalOnValueDeleted()
		{
			EntityId_Index.Remove(EntityId);
			Identity_Index.Remove(Identity);
		}

		public static PlayerComponent? FindByEntityId(ulong value)
		{
			EntityId_Index.TryGetValue(value, out var r);
			return r;
		}

		public static IEnumerable<PlayerComponent> FilterByEntityId(ulong value)
		{
			if (FindByEntityId(value) is {} found)
			{
				yield return found;
			}
		}

		public static PlayerComponent? FindByIdentity(SpacetimeDB.Identity value)
		{
			Identity_Index.TryGetValue(value, out var r);
			return r;
		}

		public static IEnumerable<PlayerComponent> FilterByIdentity(SpacetimeDB.Identity value)
		{
			if (FindByIdentity(value) is {} found)
			{
				yield return found;
			}
		}

		public static IEnumerable<PlayerComponent> FilterByLoggedIn(bool value)
		{
			return Query(x => x.LoggedIn == value);
		}

		public override object GetPrimaryKeyValue() => EntityId;

	}
}
