// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	public partial class SendChatMessageArgsStruct : IReducerArgs
	{
		ReducerType IReducerArgs.ReducerType => ReducerType.SendChatMessage;
		string IReducerArgsBase.ReducerName => "SendChatMessage";
		bool IReducerArgs.InvokeHandler(ReducerEvent reducerEvent) => Reducer.OnSendChatMessage(reducerEvent, this);

		public string Text = "";
	}

	public static partial class Reducer
	{
		public delegate void SendChatMessageHandler(ReducerEvent reducerEvent, string text);
		public static event SendChatMessageHandler? OnSendChatMessageEvent;

		public static void SendChatMessage(string text)
		{
			SpacetimeDBClient.instance.InternalCallReducer(new SendChatMessageArgsStruct { Text = text });
		}

		public static bool OnSendChatMessage(ReducerEvent reducerEvent, SendChatMessageArgsStruct args)
		{
			if (OnSendChatMessageEvent == null) return false;
			OnSendChatMessageEvent(
				reducerEvent,
				args.Text
			);
			return true;
		}
	}

}
