// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	public partial class UpdatePlayerPositionArgsStruct : IReducerArgs
	{
		ReducerType IReducerArgs.ReducerType => ReducerType.UpdatePlayerPosition;
		string IReducerArgsBase.ReducerName => "UpdatePlayerPosition";
		bool IReducerArgs.InvokeHandler(ReducerEvent reducerEvent) => Reducer.OnUpdatePlayerPosition(reducerEvent, this);

		public SpacetimeDB.Types.StdbVector3 Position = new();
		public float Direction;
		public bool Moving;
	}

	public static partial class Reducer
	{
		public delegate void UpdatePlayerPositionHandler(ReducerEvent reducerEvent, SpacetimeDB.Types.StdbVector3 position, float direction, bool moving);
		public static event UpdatePlayerPositionHandler? OnUpdatePlayerPositionEvent;

		public static void UpdatePlayerPosition(SpacetimeDB.Types.StdbVector3 position, float direction, bool moving)
		{
			SpacetimeDBClient.instance.InternalCallReducer(new UpdatePlayerPositionArgsStruct { Position = position, Direction = direction, Moving = moving });
		}

		public static bool OnUpdatePlayerPosition(ReducerEvent reducerEvent, UpdatePlayerPositionArgsStruct args)
		{
			if (OnUpdatePlayerPositionEvent == null) return false;
			OnUpdatePlayerPositionEvent(
				reducerEvent,
				args.Position,
				args.Direction,
				args.Moving
			);
			return true;
		}
	}

}
